appREST/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    url(r'^plans/$', views.ProductList.as_view()),      #GET de Products
    url(r'^payment/$', views.PaymentList.as_view()),    #GET e POST de Payments
]

pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new_payment/$', views.new_payment, name='new_payment'),
    url(r'^new_payment/(?P<plan_id>\d+)/$', views.new_payment, name='new_payment_id')
]

projetoREST/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from appREST import urls as appRest_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'^', include(appRest_urls)),
]

appREST/models.py
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.core.exceptions import ValidationError

class Product(models.Model):
    '''Produto da empresa'''

    product =       models.CharField(max_length=50)
    price =         models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    description =   models.CharField(max_length=100)

    class Meta:
        verbose_name = "Product"

    def __str__(self):
        return self.product

    @property
    def name(self):
        return self.product.replace("_", " ").title()


def myUnique(value):
    transaction_ids = Payment.objects.values_list('transaction_id', flat=True)
    if value in transaction_ids:
        raise ValidationError("Já existe uma transação com esse ID. Experimente usar: {}.".format(max(transaction_ids)+1))

class Payment(models.Model):
    '''Pagamento da empresa'''

    PAYMENT_TYPE_CHOICES = (
        ('CT', 'Cartao'),
        ('BL', 'Boleto')
    )

    payment_date =      models.DateField()
    payment_type =      models.CharField(max_length=2, choices=PAYMENT_TYPE_CHOICES)
    product =           models.ForeignKey(Product)
    product_price =     models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    discount =          models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0')),
                                                                                    MaxValueValidator(Decimal('50.00'))])
    transaction_id =    models.PositiveIntegerField(validators=[myUnique])

    #product_price deve ser armazenado, pois o valor do produto pode mudar
    # (e aqui devemos guardar o valor da época da compra)

    #Price não precisam ser armazenados no banco de dados,
    #podendo ser derivados de outros campos.
    #Por isso são representados como propriedades.

    @property
    def price(self):
        return Decimal(self.product_price * (1-(self.discount/100)))

    class Meta:
        verbose_name = "Payment"

    def __str__(self):
        return str(self.transaction_id) + " | " + str(self.payment_date) + " | " + str(self.product)

pages/models.py
from django.db import models

# Create your models here.

appREST/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Product, Payment
from .serializers import ProductSerializer, PaymentSerializer

class ProductList(APIView):
    '''Mostra todos os produtos'''

    def get(self, request, format=None):
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return  Response(serializer.data)

class PaymentList(APIView):
    '''Mostra os pagamentos e permite criar um novo'''

    def get(self, request, format=None):
        payments = Payment.objects.all()
        serializer = PaymentSerializer(payments, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = PaymentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return  Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

pages/views.py
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

def index(request):
    return render(request, 'index.html')

@ensure_csrf_cookie
def new_payment(request, plan_id='0'):
    context = {'plan_id': plan_id}
    return render(request, 'new_payment.html', context)

pages/templates/base.html
<!DOCTYPE html>
<html lang="pt">
<head>
	{% load static %}
	<!--Descrição-->
	<title>Site Empresa</title>
	<meta charset="utf-8">
	<meta name="author" content="Guilherme José Acra">
	<meta name="description" content="Veja aqui os planos da Empresa disponíveis para compra.">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!--Folhas de estilo (Bootstrap e personalizada)-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static "style.css" %}">

	<!--Scripts (JQuery, Knockout, Bootstrap)-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
	<script src="http://ajax.aspnetcdn.com/ajax/knockout/knockout-3.4.2.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</head>
<body style="padding-top: 80px">

	<!--Menu de navegação-->
	<nav class="navbar navbar-expand-sm navbar-dark fixed-top" style="background-color: rgb(66, 103, 178);">
		<a class="navbar-brand" href="{% url 'pages:index' %}">
			<span class="brand-title">Empresa</span>
		</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		 	<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		 <div class="navbar-nav ml-auto" >
		  <a class="nav-item nav-link item-white" href="{% url 'pages:index' %}">Produtos</a>
		  <a class="nav-item nav-link item-white" href="{% url 'pages:new_payment' %}">Novo Pagamento</a>
		 </div>
		</div>
	</nav>

    {% block content %}
    {% endblock content %}

</body>
</html>

pages/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<!--Título da página-->
	<header>
		<div class="jumbotron jumbotron-fluid py-4">
		  <div class="container mx-4">
		    <h1 class="display-3">Produtos</h1>    
		  </div>
		</div>
	</header>

	<!--Corpo da página-->
	<main>

		<!--Apresentação dos produtos na forma de cartões (preenchido automaticamente pelo Knockout)-->
		<div class="container-fluid" id="div_plans" style="display: none;">

			<div class="row mb-4">

				<!-- ko foreach: plans -->
				<div class="col-lg-4 col-md-6 col-sm-6 col-12 px-2 mx-auto">
					<div class="card my-1">
						<h2 class="card-header text-truncate" data-bind="text: name"></h2>
						<ul class="list-group list-group-flush">
					    <li class="list-group-item" data-bind="text: product"></li>
					    <li class="list-group-item">R$ <span data-bind="text: price"></span></li>
					   	<li class="list-group-item text-truncate" data-bind="text: description" id="description"></li>
					  </ul>
					  <div class="card-body">
					    <a data-bind='attr: { href: url}' class="btn">Comprar</a>
					  </div>
					</div> <!-- /card-->
				</div> <!-- /div-card-->
				<!-- /ko -->			

			</div> <!-- /row-->			

		</div> <!-- /container-fluid-->

	</main>

	<!--Script personalizado-->
	<script src="{% static "index.js" %}"></script>
{% endblock content %}

pages/templates/new_payment.html
{% extends "base.html" %}
{% load static %}
{% block content %}

	<!--Título da página-->
	<div class="jumbotron jumbotron-fluid py-4">
	  <div class="container mx-4">
	    <h1 class="display-3">Novo Pagamento</h1>    
	  </div>
	</div>

	<!--Corpo da página-->
	<main>

		<div class="container">

			<!--Formulário de Novo Pagamento-->
			<form accept-charset="utf-8" class="form-horizontal mx-auto pb-4" id="needs-validation" novalidate>

				<!--Data do pagamento-->
				<div class="form-group">
			    <label for="payment_date">Data do Pagamento:</label>
					<input type="date" name="payment_date" id="payment_date" class="form-control" required>
					<div class="invalid-feedback">
	      			<p>Entre com uma data válida.</p>
	      	</div>
			  </div>

			  <!--Produto-->
				<div class="form-group">
			    <label for="product">Produto:</label>
			    <select name="product" id="product" class="form-control">
			    	<!-- ko foreach: plans -->
			      <option data-bind="text: name, value: id"></option>
			      <!-- /ko -->	
			    </select>
			  </div>

			  <!--Valor do produto-->
			  <div class="form-group">
			    <label for="product_price">Valor do Produto (R$):</label>
					<input type="number" name="product_price" id="product_price" class="form-control" min="0.01" max="1000" step="0.01" value="0.01" readonly>
					<div class="invalid-feedback">
	      			<p>Entre com um preço válido.</p>
	      	</div>
			  </div>

			  <!--Desconto-->
				<div class="form-group">
			    <label for="discount">Desconto (%):</label>
					<input type="number" name="discount" id="discount" class="form-control" min="0" max="50" step="1" value="0" required>
					<div class="invalid-feedback">
	      		<p>O disconto deve ser um número inteiro e não deve passar de 50%.</p>
	      	</div>
			  </div>

			  <!--Valor do pagamento-->
				<div class="form-group">
			    <label for="price">Valor do Pagamento com Desconto (R$):</label>
					<input type="number" name="price" id="price" class="form-control" value="0.01" readonly>
			  </div>

			  <!--Tipo do pagamento-->
				<div class="form-check form-check-inline">
				  <label class="form-check-label">
				    <input class="form-check-input" type="radio" name="payment_type" id="cartao" value="CT" checked> Cartão
				  </label>
				</div>
				<div class="form-check form-check-inline">
				  <label class="form-check-label">
				    <input class="form-check-input" type="radio" name="payment_type" id="boleto" value="BL"> Boleto
				  </label>
				</div>

				<!--ID da transação-->
				<div class="form-group">
			    <label for="transaction_id">ID da transação:</label>
					<input type="number" name="transaction_id" id="transaction_id" class="form-control" min="0" step="1" required>
					<div class="invalid-feedback">
	      		<p>O ID deve ser um número inteiro e positivo.</p>
	      	</div>
	      	<div class="invalid-id"></div>
			  </div>

				<!--Botão (Fazer pagamento)-->
				<button class="btn d-block">Fazer pagamento</button>

				<div class="unknow_error text-danger" style="display: none;">
				</div>

			</form>

		</div> <!-- /container-->

		<!--Modal para confirmação do pagamento-->
		<div class="modal t-modal animated" id="modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h3 class="modal-title">PAGAMENTO EFETUADO</h3>
					</div>
					<div class="modal-body text-center">
						Agradecemos a preferência.
					</div>
					<div class="modal-footer mx-auto">
						<a href="{% url 'pages:index' %}" class="badge" style="padding: 1em; font-size: 0.9em">  Voltar aos produtos  </a>
						<a href="{% url 'pages:new_payment' %}" class="badge" style="padding: 1em; font-size: 0.9em">Fazer novo pagamento</a>
					</div>
				</div><!-- /.modal-content-->
			</div><!-- /.modal-dialog-->
		</div><!-- ./modal-->

	</main>

	<!--Script Personalizado e inicialização de variável-->
	<script>
		var plan_id = {{ plan_id }}
	</script>
	<script src="{% static "payment.js" %}"></script>

{% endblock content %}